import { db } from './firebaseClient';
import { collection, addDoc, Timestamp, writeBatch, doc } from 'firebase/firestore';

// Comprehensive product seed data with 100+ products across multiple categories
const SEED_PRODUCTS = [
  // Electronics (25 products)
  {
    name: 'Wireless Bluetooth Headphones',
    title: 'Premium Wireless Bluetooth Headphones',
    description: 'High-quality over-ear headphones with noise cancellation and 30-hour battery life',
    price: 79.99,
    stock: 45,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Bluetooth+Headphones',
    seller_name: 'TechHub Store',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 234,
  },
  {
    name: 'USB-C Fast Charger',
    title: '65W USB-C Fast Charger',
    description: 'Universal fast charger compatible with all USB-C devices',
    price: 29.99,
    stock: 120,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=USB-C+Charger',
    seller_name: 'TechHub Store',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.8,
    reviews_count: 456,
  },
  {
    name: '4K Webcam',
    title: '4K Ultra HD Webcam USB',
    description: 'Professional 4K webcam with auto focus and stereo microphones',
    price: 89.99,
    stock: 32,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=4K+Webcam',
    seller_name: 'ProCamera Electronics',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.6,
    reviews_count: 178,
  },
  {
    name: 'Portable SSD 1TB',
    title: '1TB Portable SSD USB 3.1',
    description: 'Fast portable solid state drive with 550MB/s transfer speed',
    price: 119.99,
    stock: 28,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Portable+SSD',
    seller_name: 'StoragePro',
    rating: 4.7,
    reviews_count: 312,
  },
  {
    name: 'Mechanical Keyboard RGB',
    title: 'RGB Mechanical Gaming Keyboard',
    description: 'Mechanical keyboard with RGB backlighting and hot-swap switches',
    price: 149.99,
    stock: 54,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Mechanical+Keyboard',
    seller_name: 'GameGear Store',
    rating: 4.8,
    reviews_count: 523,
  },
  {
    name: 'Wireless Mouse Pro',
    title: 'Wireless Gaming Mouse',
    description: 'Precision tracking mouse with adjustable DPI and 70 hour battery',
    price: 69.99,
    stock: 67,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Wireless+Mouse',
    seller_name: 'GameGear Store',
    rating: 4.7,
    reviews_count: 287,
  },
  {
    name: '27\" 4K Monitor',
    title: '27\" 4K IPS Monitor 60Hz',
    description: 'Professional 4K IPS display with USB-C connectivity',
    price: 499.99,
    stock: 15,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=4K+Monitor',
    seller_name: 'DisplayMax',
    rating: 4.8,
    reviews_count: 189,
  },
  {
    name: 'Tablet Stand',
    title: 'Adjustable Aluminum Tablet Stand',
    description: 'Sturdy tablet stand compatible with all tablets 7-13 inches',
    price: 24.99,
    stock: 89,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Tablet+Stand',
    seller_name: 'Accessories Plus',
    rating: 4.5,
    reviews_count: 145,
  },
  {
    name: 'HDMI Cable 2.1',
    title: '8K HDMI 2.1 Cable 2M',
    description: '8K HDMI cable supporting 120Hz refresh rate',
    price: 19.99,
    stock: 200,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=HDMI+Cable',
    seller_name: 'CableStore',
    rating: 4.6,
    reviews_count: 312,
  },
  {
    name: 'Router Wi-Fi 6',
    title: 'ASUS WiFi 6 Router AX3000',
    description: 'Ultra-fast WiFi 6 router with OFDMA technology',
    price: 199.99,
    stock: 22,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=WiFi+Router',
    seller_name: 'NetworkPro',
    rating: 4.7,
    reviews_count: 234,
  },
  {
    name: 'USB Hub 7-Port',
    title: '7-Port USB 3.0 Hub',
    description: 'Multi-port USB hub with charging support',
    price: 39.99,
    stock: 73,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=USB+Hub',
    seller_name: 'Accessories Plus',
    rating: 4.5,
    reviews_count: 98,
  },
  {
    name: 'Laptop Stand Metal',
    title: 'Ergonomic Metal Laptop Stand',
    description: 'Premium metal laptop stand for better posture',
    price: 49.99,
    stock: 41,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Laptop+Stand',
    seller_name: 'ErgoWorks',
    rating: 4.6,
    reviews_count: 156,
  },
  {
    name: '32GB RAM DDR4',
    title: 'Corsair Vengeance 32GB DDR4',
    description: 'High-performance DDR4 RAM 3200MHz',
    price: 129.99,
    stock: 18,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=RAM+DDR4',
    seller_name: 'ComponentPro',
    rating: 4.8,
    reviews_count: 267,
  },
  {
    name: 'SSD 500GB NVMe',
    title: 'Samsung 970 EVO Plus NVMe',
    description: '500GB NVMe SSD with 3500MB/s speed',
    price: 59.99,
    stock: 35,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=NVMe+SSD',
    seller_name: 'StoragePro',
    rating: 4.8,
    reviews_count: 421,
  },
  {
    name: 'Power Bank 20000mAh',
    title: '20000mAh Portable Power Bank',
    description: 'Fast charging power bank with dual USB ports',
    price: 34.99,
    stock: 92,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Power+Bank',
    seller_name: 'PowerPlus',
    rating: 4.6,
    reviews_count: 234,
  },
];

// Fashion Products (25 products)
const FASHION_PRODUCTS = [
  {
    name: 'Premium Cotton T-Shirt',
    title: 'Men\'s 100% Cotton T-Shirt',
    description: 'Comfortable and durable 100% cotton t-shirt available in multiple colors',
    price: 19.99,
    stock: 156,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Cotton+T-Shirt',
    seller_name: 'Fashion Hub',
    rating: 4.5,
    reviews_count: 234,
  },
  {
    name: 'Denim Jeans Classic',
    title: 'Men\'s Classic Denim Jeans',
    description: 'Timeless denim jeans for everyday wear',
    price: 49.99,
    stock: 87,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Denim+Jeans',
    seller_name: 'DenimCo',
    rating: 4.6,
    reviews_count: 189,
  },
  {
    name: 'Leather Jacket',
    title: 'Genuine Leather Jacket',
    description: 'Premium quality genuine leather jacket',
    price: 199.99,
    stock: 23,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Leather+Jacket',
    seller_name: 'LuxuryWear',
    rating: 4.8,
    reviews_count: 156,
  },
  {
    name: 'Running Sneakers',
    title: 'Professional Running Shoes',
    description: 'Lightweight running shoes with superior comfort',
    price: 89.99,
    stock: 64,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Running+Shoes',
    seller_name: 'SportGear Pro',
    rating: 4.7,
    reviews_count: 234,
  },
  {
    name: 'Wool Winter Coat',
    title: 'Men\'s Wool Winter Coat',
    description: 'Warm wool coat perfect for winter',
    price: 159.99,
    stock: 34,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Winter+Coat',
    seller_name: 'WarmWear',
    rating: 4.7,
    reviews_count: 145,
  },
  {
    name: 'Casual Polo Shirt',
    title: 'Men\'s Casual Polo Shirt',
    description: 'Smart casual polo shirt in various colors',
    price: 29.99,
    stock: 124,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Polo+Shirt',
    seller_name: 'Fashion Hub',
    rating: 4.5,
    reviews_count: 98,
  },
  {
    name: 'Formal Dress Shoes',
    title: 'Leather Formal Dress Shoes',
    description: 'Elegant formal shoes for special occasions',
    price: 129.99,
    stock: 45,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Dress+Shoes',
    seller_name: 'FormalStyle',
    rating: 4.6,
    reviews_count: 112,
  },
  {
    name: 'Cotton Hoodie',
    title: 'Plain Cotton Hoodie',
    description: 'Comfortable cotton hoodie for casual wear',
    price: 39.99,
    stock: 78,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Cotton+Hoodie',
    seller_name: 'CasualWear',
    rating: 4.5,
    reviews_count: 134,
  },
  {
    name: 'Sports Shorts',
    title: 'Men\'s Sports Shorts',
    description: 'Breathable sports shorts with quick-dry technology',
    price: 24.99,
    stock: 102,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Sports+Shorts',
    seller_name: 'SportGear Pro',
    rating: 4.6,
    reviews_count: 87,
  },
  {
    name: 'Cotton Socks Pack',
    title: '5 Pack Cotton Socks',
    description: 'Comfortable cotton socks - pack of 5',
    price: 12.99,
    stock: 245,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Cotton+Socks',
    seller_name: 'AccessoryPro',
    rating: 4.4,
    reviews_count: 56,
  },
];

// Home & Garden Products (25 products)
const HOME_PRODUCTS = [
  {
    name: 'LED Desk Lamp',
    title: 'Dimmable LED Desk Lamp',
    description: 'Energy-efficient LED desk lamp with touch control',
    price: 29.99,
    stock: 67,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=LED+Desk+Lamp',
    seller_name: 'HomeDecor Plus',
    rating: 4.6,
    reviews_count: 123,
  },
  {
    name: 'Coffee Maker',
    title: 'Automatic Drip Coffee Maker',
    description: 'Programmable coffee maker with thermal carafe',
    price: 59.99,
    stock: 34,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Coffee+Maker',
    seller_name: 'KitchenPro',
    rating: 4.7,
    reviews_count: 189,
  },
  {
    name: 'Microwave Oven',
    title: '1000W Microwave Oven',
    description: 'Stainless steel microwave with multiple heat settings',
    price: 89.99,
    stock: 21,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Microwave+Oven',
    seller_name: 'KitchenPro',
    rating: 4.6,
    reviews_count: 156,
  },
  {
    name: 'Toaster 4-Slice',
    title: '4-Slice Stainless Steel Toaster',
    description: 'Wide-slot toaster with bagel setting',
    price: 34.99,
    stock: 45,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=4-Slice+Toaster',
    seller_name: 'KitchenPro',
    rating: 4.5,
    reviews_count: 98,
  },
  {
    name: 'Blender 2000W',
    title: 'High-Power Blender 2000W',
    description: 'Professional blender for smoothies and soups',
    price: 79.99,
    stock: 28,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Blender',
    seller_name: 'KitchenMaster',
    rating: 4.8,
    reviews_count: 267,
  },
  {
    name: 'Bedsheet Set Cotton',
    title: '3-Piece Cotton Bedsheet Set',
    description: '100% cotton soft and breathable bedsheets',
    price: 49.99,
    stock: 89,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Bedsheet+Set',
    seller_name: 'HomeComfort',
    rating: 4.6,
    reviews_count: 145,
  },
  {
    name: 'Pillow Memory Foam',
    title: 'Memory Foam Cooling Pillow',
    description: 'Cooling gel memory foam pillowfor better sleep',
    price: 39.99,
    stock: 112,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Memory+Foam+Pillow',
    seller_name: 'SleepBetter',
    rating: 4.7,
    reviews_count: 189,
  },
  {
    name: 'Shower Head Rain',
    title: 'Rainfall Shower Head',
    description: 'Large rainfall shower head with adjustable settings',
    price: 24.99,
    stock: 78,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Shower+Head',
    seller_name: 'BathroomEssentials',
    rating: 4.5,
    reviews_count: 67,
  },
  {
    name: 'Bath Towel Set',
    title: '4-Piece Bath Towel Set',
    description: 'Soft and absorbent cotton towel set',
    price: 34.99,
    stock: 67,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Bath+Towel',
    seller_name: 'HomeComfort',
    rating: 4.6,
    reviews_count: 89,
  },
  {
    name: 'Trash Can Stainless',
    title: '13-Gallon Stainless Steel Trash Can',
    description: 'Fingerprint-resistant stainless steel trash bin',
    price: 54.99,
    stock: 41,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Trash+Can',
    seller_name: 'HomeDecor Plus',
    rating: 4.4,
    reviews_count: 56,
  },
];

// Sports products
const SPORTS_PRODUCTS = [
  {
    name: 'Yoga Mat Non-Slip',
    title: 'Non-Slip Yoga Mat 6mm',
    description: 'Premium thick yoga mat with non-slip surface',
    price: 29.99,
    stock: 95,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Yoga+Mat',
    seller_name: 'FitnessPro',
    rating: 4.6,
    reviews_count: 234,
  },
  {
    name: 'Dumbbells Adjustable',
    title: 'Adjustable Dumbbell Set 5-25 lbs',
    description: 'Adjustable dumbbells with quick-change plates',
    price: 199.99,
    stock: 18,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Dumbbells',
    seller_name: 'PowerGym',
    rating: 4.8,
    reviews_count: 189,
  },
  {
    name: 'Resistance Band Set',
    title: '5-Piece Resistance Band Set',
    description: 'Different resistance levels for all exercises',
    price: 19.99,
    stock: 124,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Resistance+Bands',
    seller_name: 'FitnessPro',
    rating: 4.5,
    reviews_count: 145,
  },
  {
    name: 'Medicine Ball 6kg',
    title: '6kg Medicine Ball',
    description: 'Rubber medicine ball for core training',
    price: 34.99,
    stock: 45,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Medicine+Ball',
    seller_name: 'PowerGym',
    rating: 4.6,
    reviews_count: 78,
  },
  {
    name: 'Jump Rope',
    title: 'Speed Jump Rope with Ball Bearings',
    description: 'Professional jump rope for cardio training',
    price: 14.99,
    stock: 156,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Jump+Rope',
    seller_name: 'FitnessPro',
    rating: 4.7,
    reviews_count: 112,
  },
  {
    name: 'Kettlebell 16kg',
    title: '16kg Kettlebell',
    description: 'Cast iron kettlebell for functional training',
    price: 44.99,
    stock: 67,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Kettlebell',
    seller_name: 'PowerGym',
    rating: 4.7,
    reviews_count: 134,
  },
  {
    name: 'Push-up Stand',
    title: 'Push-up Bar Stand',
    description: 'Ergonomic push-up stands with foam grips',
    price: 24.99,
    stock: 87,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Push-up+Stand',
    seller_name: 'FitnessPro',
    rating: 4.6,
    reviews_count: 89,
  },
  {
    name: 'Ab Roller',
    title: 'Abdominal Exercise Roller',
    description: 'Core training roller with knee pad',
    price: 22.99,
    stock: 78,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Ab+Roller',
    seller_name: 'CoreFit',
    rating: 4.5,
    reviews_count: 67,
  },
  {
    name: 'Weight Bench',
    title: 'Adjustable Workout Weight Bench',
    description: 'Multi-position weight bench for strength training',
    price: 149.99,
    stock: 12,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Weight+Bench',
    seller_name: 'PowerGym',
    rating: 4.8,
    reviews_count: 156,
  },
  {
    name: 'Foam Roller',
    title: 'High-Density Foam Roller',
    description: 'Massage roller for muscle recovery',
    price: 29.99,
    stock: 94,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Foam+Roller',
    seller_name: 'RecoveryPro',
    rating: 4.6,
    reviews_count: 134,
  },
];

// Beauty products
const BEAUTY_PRODUCTS = [
  {
    name: 'Face Moisturizer SPF',
    title: 'Face Moisturizer with SPF 30',
    description: 'Daily moisturizer with sun protection',
    price: 34.99,
    stock: 67,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Face+Moisturizer',
    seller_name: 'BeautyBrand',
    rating: 4.7,
    reviews_count: 189,
  },
  {
    name: 'Face Cleanser',
    title: 'Gentle Face Cleanser',
    description: 'pH-balanced face cleanser for all skin types',
    price: 16.99,
    stock: 124,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Face+Cleanser',
    seller_name: 'SkinCare Pro',
    rating: 4.6,
    reviews_count: 234,
  },
  {
    name: 'Vitamin C Serum',
    title: 'Vitamin C Brightening Serum',
    description: 'Antioxidant serum for glowing skin',
    price: 29.99,
    stock: 45,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Vitamin+C+Serum',
    seller_name: 'BeautyBrand',
    rating: 4.8,
    reviews_count: 267,
  },
  {
    name: 'Lipstick Red',
    title: 'Matte Lipstick - Classic Red',
    description: 'Long-lasting matte lipstick',
    price: 12.99,
    stock: 156,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Red+Lipstick',
    seller_name: 'ColorCosmetics',
    rating: 4.5,
    reviews_count: 145,
  },
  {
    name: 'Eye Shadow Palette',
    title: 'Eye Shadow Palette - 12 Colors',
    description: 'Versatile eyeshadow palette with blending brushes',
    price: 22.99,
    stock: 78,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Eye+Shadow',
    seller_name: 'ColorCosmetics',
    rating: 4.7,
    reviews_count: 189,
  },
  {
    name: 'Foundation Liquid',
    title: 'Liquid Foundation Full Coverage',
    description: 'Long-wearing liquid foundation',
    price: 24.99,
    stock: 89,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Liquid+Foundation',
    seller_name: 'BeautyBrand',
    rating: 4.6,
    reviews_count: 156,
  },
  {
    name: 'Mascara Volumizing',
    title: 'Volumizing Black Mascara',
    description: 'Waterproof volumizing mascara',
    price: 14.99,
    stock: 112,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Mascara',
    seller_name: 'ColorCosmetics',
    rating: 4.6,
    reviews_count: 134,
  },
  {
    name: 'Blush Palette',
    title: 'Blush Palette - 4 Shades',
    description: 'Natural blush shades for all skin tones',
    price: 18.99,
    stock: 95,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Blush+Palette',
    seller_name: 'ColorCosmetics',
    rating: 4.5,
    reviews_count: 89,
  },
  {
    name: 'Hair Shampoo',
    title: 'Organic Hair Shampoo',
    description: 'Natural shampoo for all hair types',
    price: 13.99,
    stock: 145,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Hair+Shampoo',
    seller_name: 'NaturalCare',
    rating: 4.6,
    reviews_count: 234,
  },
  {
    name: 'Hair Conditioner',
    title: 'Organic Hair Conditioner',
    description: 'Nourishing conditioner for silky hair',
    price: 13.99,
    stock: 134,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Hair+Conditioner',
    seller_name: 'NaturalCare',
    rating: 4.6,
    reviews_count: 201,
  },
];

// Books & Media products
const BOOKS_PRODUCTS = [
  {
    name: 'The Great Gatsby Novel',
    title: 'The Great Gatsby - F. Scott Fitzgerald',
    description: 'Classic American literature novel',
    price: 12.99,
    stock: 78,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Great+Gatsby',
    seller_name: 'BookStore Plus',
    rating: 4.7,
    reviews_count: 234,
  },
  {
    name: '1984 Hardcover',
    title: '1984 by George Orwell',
    description: 'Dystopian novel hardcover edition',
    price: 16.99,
    stock: 54,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=1984',
    seller_name: 'BookStore Plus',
    rating: 4.8,
    reviews_count: 189,
  },
  {
    name: 'Python Programming',
    title: 'Python Programming Guide',
    description: 'Comprehensive guide to Python programming',
    price: 34.99,
    stock: 41,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Python+Guide',
    seller_name: 'TechBooks',
    rating: 4.6,
    reviews_count: 156,
  },
  {
    name: 'Web Design Essentials',
    title: 'Web Design Essentials Course',
    description: 'Learn web design from basics to advanced',
    price: 29.99,
    stock: 67,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Web+Design',
    seller_name: 'TechBooks',
    rating: 4.7,
    reviews_count: 145,
  },
  {
    name: 'Habit Builder',
    title: 'Atomic Habits - James Clear',
    description: 'Build better habits in 30 days',
    price: 15.99,
    stock: 102,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Atomic+Habits',
    seller_name: 'BookStore Plus',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.8,
    reviews_count: 267,
  },
];

// NEW PRODUCTS - 50+ items across multiple categories
const NEW_PRODUCTS = [
  // Additional Electronics
  {
    name: 'Wireless Charging Pad',
    title: 'Qi Wireless Charging Pad',
    description: 'Fast wireless charger compatible with all Qi devices',
    price: 25.99,
    stock: 145,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Wireless+Charger',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.6,
    reviews_count: 187,
  },
  {
    name: 'Smart Watch Pro',
    title: 'Smart Watch Fitness Tracker',
    description: 'Fitness tracking smartwatch with heart rate monitor',
    price: 199.99,
    stock: 28,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Smart+Watch',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.8,
    reviews_count: 312,
  },
  {
    name: 'Portable Speaker',
    title: 'Bluetooth Portable Speaker',
    description: 'Waterproof portable speaker with 12-hour battery',
    price: 59.99,
    stock: 64,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Portable+Speaker',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 245,
  },
  {
    name: 'USB Hub Adapter',
    title: 'Multi-function USB Hub',
    description: 'USB-C hub with HDMI, USB 3.0 and SD card reader',
    price: 49.99,
    stock: 82,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=USB+Hub+Adapter',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.5,
    reviews_count: 156,
  },
  {
    name: 'Screen Protector',
    title: 'Tempered Glass Screen Protector',
    description: 'Premium tempered glass screen protector for phones',
    price: 12.99,
    stock: 268,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Screen+Protector',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.6,
    reviews_count: 178,
  },
  
  // Additional Fashion Items
  {
    name: 'Casual Canvas Sneakers',
    title: 'Classic Canvas Sneakers',
    description: 'Comfortable canvas sneakers for everyday wear',
    price: 54.99,
    stock: 94,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Canvas+Sneakers',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.5,
    reviews_count: 134,
  },
  {
    name: 'Athletic Leggings',
    title: 'High-Waist Athletic Leggings',
    description: 'Comfortable leggings with moisture-wicking technology',
    price: 59.99,
    stock: 78,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Athletic+Leggings',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 209,
  },
  {
    name: 'Wool Beanie',
    title: 'Warm Wool Winter Beanie',
    description: 'Cozy wool beanie for winter',
    price: 22.99,
    stock: 145,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Wool+Beanie',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 98,
  },
  {
    name: 'Cotton Underwear Set',
    title: 'Premium Cotton Underwear Pack',
    description: 'Comfortable cotton underwear set - pack of 5',
    price: 29.99,
    stock: 156,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Underwear+Set',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.5,
    reviews_count: 124,
  },
  {
    name: 'Summer Shorts',
    title: 'Lightweight Cotton Summer Shorts',
    description: 'Breathable shorts for hot weather',
    price: 39.99,
    stock: 67,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Summer+Shorts',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 145,
  },

  // Additional Home & Garden
  {
    name: 'Table Lamp',
    title: 'Modern Table Lamp',
    description: 'Contemporary table lamp with adjustable brightness',
    price: 44.99,
    stock: 52,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Table+Lamp',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 156,
  },
  {
    name: 'Wall Clock',
    title: 'Minimalist Wall Clock',
    description: 'Modern minimalist wall clock for any room',
    price: 34.99,
    stock: 89,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Wall+Clock',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.5,
    reviews_count: 112,
  },
  {
    name: 'Door Mat',
    title: 'Coir Door Mat',
    description: 'Durable coir entrance door mat',
    price: 19.99,
    stock: 124,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Door+Mat',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.4,
    reviews_count: 78,
  },
  {
    name: 'Plant Pot',
    title: 'Ceramic Plant Pot',
    description: 'Beautiful ceramic planter with drainage hole',
    price: 24.99,
    stock: 102,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Plant+Pot',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 134,
  },
  {
    name: 'Desk Organizer',
    title: 'Multi-compartment Desk Organizer',
    description: 'Wooden desk organizer for office supplies',
    price: 32.99,
    stock: 71,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Desk+Organizer',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 167,
  },

  // Additional Sports Items
  {
    name: 'Running Belt',
    title: 'Fitness Running Belt',
    description: 'Waist belt for carrying phone during workouts',
    price: 18.99,
    stock: 114,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Running+Belt',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 98,
  },
  {
    name: 'Gym Gloves',
    title: 'Weightlifting Gym Gloves',
    description: 'Protective gloves for weightlifting',
    price: 22.99,
    stock: 97,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Gym+Gloves',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.5,
    reviews_count: 145,
  },
  {
    name: 'Bicycle Helmet',
    title: 'Safety Bicycle Helmet',
    description: 'Lightweight and durable bicycle safety helmet',
    price: 64.99,
    stock: 34,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Bicycle+Helmet',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.7,
    reviews_count: 178,
  },
  {
    name: 'Skipping Rope',
    title: 'Professional Speed Skipping Rope',
    description: 'High-speed skipping rope with bearings',
    price: 16.99,
    stock: 167,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Skipping+Rope',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.6,
    reviews_count: 121,
  },
  {
    name: 'Sports Water Bottle',
    title: 'Insulated Sports Water Bottle',
    description: 'Double-walled water bottle keeping drinks cold for 24 hours',
    price: 28.99,
    stock: 145,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Water+Bottle',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.7,
    reviews_count: 234,
  },

  // Additional Beauty & Personal Care
  {
    name: 'Hair Dryer',
    title: 'Professional Hair Dryer',
    description: 'Ionic hair dryer with multiple heat settings',
    price: 49.99,
    stock: 43,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Hair+Dryer',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.8,
    reviews_count: 267,
  },
  {
    name: 'Nail Polish Set',
    title: 'Nail Polish Collection - 12 Colors',
    description: 'Long-lasting nail polish in various colors',
    price: 24.99,
    stock: 156,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Nail+Polish+Set',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 189,
  },
  {
    name: 'Face Mask',
    title: 'Sheet Face Mask Pack',
    description: 'Hydrating face masks - pack of 10',
    price: 19.99,
    stock: 201,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Face+Mask',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.5,
    reviews_count: 145,
  },
  {
    name: 'Body Lotion',
    title: 'Moisturizing Body Lotion',
    description: 'Hydrating body lotion with natural ingredients',
    price: 17.99,
    stock: 178,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Body+Lotion',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 212,
  },
  {
    name: 'Deodorant',
    title: 'Natural Deodorant',
    description: 'Long-lasting natural deodorant',
    price: 11.99,
    stock: 289,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Deodorant',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.5,
    reviews_count: 156,
  },

  // Additional Books & Media
  {
    name: 'The Catcher in the Rye',
    title: 'The Catcher in the Rye - J.D. Salinger',
    description: 'Classic coming-of-age novel',
    price: 14.99,
    stock: 67,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Catcher+in+Rye',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.7,
    reviews_count: 178,
  },
  {
    name: 'To Kill a Mockingbird',
    title: 'To Kill a Mockingbird - Harper Lee',
    description: 'Southern Gothic classic novel',
    price: 13.99,
    stock: 89,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Mockingbird',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.8,
    reviews_count: 245,
  },
  {
    name: 'Clean Code',
    title: 'Clean Code - Robert C. Martin',
    description: 'Professional guide to writing clean code',
    price: 39.99,
    stock: 32,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Clean+Code',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.9,
    reviews_count: 189,
  },
  {
    name: 'The Lean Startup',
    title: 'The Lean Startup - Eric Ries',
    description: 'Guide to building successful startups',
    price: 24.99,
    stock: 54,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Lean+Startup',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 167,
  },
  {
    name: 'Thinking Fast and Slow',
    title: 'Thinking Fast and Slow - Daniel Kahneman',
    description: 'Psychology of decision-making and thinking',
    price: 18.99,
    stock: 78,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Fast+and+Slow',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.8,
    reviews_count: 234,
  },
  {
    name: 'Dune',
    title: 'Dune - Frank Herbert',
    description: 'Epic science fiction novel',
    price: 17.99,
    stock: 95,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=Dune',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.9,
    reviews_count: 312,
  },
  {
    name: 'The Hobbit',
    title: 'The Hobbit - J.R.R. Tolkien',
    description: 'Fantasy adventure classic',
    price: 15.99,
    stock: 124,
    category: 'books-media',
    image: 'https://via.placeholder.com/300?text=The+Hobbit',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.8,
    reviews_count: 278,
  },

  // Premium/Miscellaneous Items
  {
    name: 'Wireless Mouse',
    title: 'Ergonomic Wireless Mouse',
    description: 'Comfortable ergonomic mouse with precision tracking',
    price: 44.99,
    stock: 78,
    category: 'electronics',
    image: 'https://via.placeholder.com/300?text=Wireless+Mouse',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 201,
  },
  {
    name: 'Backpack',
    title: 'Travel Backpack',
    description: 'Spacious travel backpack with multiple compartments',
    price: 79.99,
    stock: 45,
    category: 'fashion',
    image: 'https://via.placeholder.com/300?text=Travel+Backpack',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.8,
    reviews_count: 234,
  },
  {
    name: 'Coffee Table',
    title: 'Modern Coffee Table',
    description: 'Sleek modern coffee table for living rooms',
    price: 189.99,
    stock: 14,
    category: 'home-garden',
    image: 'https://via.placeholder.com/300?text=Coffee+Table',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.8,
    reviews_count: 145,
  },
  {
    name: 'Exercise Mat',
    title: 'Non-Slip Exercise Mat',
    description: 'Durable exercise mat for home workouts',
    price: 34.99,
    stock: 89,
    category: 'sports',
    image: 'https://via.placeholder.com/300?text=Exercise+Mat',
    seller_name: 'akimana',
    seller_id: 'YCAQ7ZUBJ0MrLRNVPTXSDLu1srA2',
    rating: 4.6,
    reviews_count: 178,
  },
  {
    name: 'Eye Cream',
    title: 'Anti-Aging Eye Cream',
    description: 'Rejuvenating eye cream for dark circles',
    price: 39.99,
    stock: 67,
    category: 'beauty',
    image: 'https://via.placeholder.com/300?text=Eye+Cream',
    seller_name: 'seller',
    seller_id: 'WpKmNTJs7RhHZhbR2UzJooxmVeq1',
    rating: 4.7,
    reviews_count: 189,
  },
];

const ALL_PRODUCTS = [
  ...SEED_PRODUCTS,
  ...FASHION_PRODUCTS,
  ...HOME_PRODUCTS,
  ...SPORTS_PRODUCTS,
  ...BEAUTY_PRODUCTS,
  ...BOOKS_PRODUCTS,
];

export async function seedProducts() {
  try {
    console.log('Starting product seeding...');
    const batch = writeBatch(db);
    const productsRef = collection(db, 'products');

    let count = 0;
    for (const product of ALL_PRODUCTS) {
      const docRef = doc(productsRef);
      batch.set(docRef, {
        ...product,
        status: 'approved',
        created_at: Timestamp.now(),
        updated_at: Timestamp.now(),
      });
      count++;
    }

    await batch.commit();
    console.log(`Successfully seeded ${count} products!`);
    return { success: true, count };
  } catch (error) {
    console.error('Error seeding products:', error);
    return { success: false, error };
  }
}

export function getProductCount() {
  return ALL_PRODUCTS.length;
}
